In [54]:
import torch
from torch import nn
import torchvision
from torchvision import datasets, transforms
from torch.utils.data import random_split
import numpy as np
import cv2

import skimage as ski
from skimage import color

torch.__version__

'2.1.2+cpu'

In [3]:
import os

In [5]:
# Setup device-agnostic code
device = torch.device( "cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

In [46]:
def transf_to_tensor():
    transf = transforms.Compose([transforms.ToTensor()])
    return transf

In [30]:
# transfToTensor = transforms.Compose([transforms.ToTensor()])

In [72]:
img_path = 'dataset_base/0_Amiloidose/AZAN/0_Amiloidose_AZAN_0.jpg'
img = cv2.imread(img_path)
img = transf_to_tensor()(img)
img.dtype

torch.float32

In [89]:
img.shape

torch.Size([3, 768, 1024])

In [97]:
img

tensor([[[0.7294, 0.7333, 0.7216,  ..., 0.8078, 0.8078, 0.8039],
         [0.7294, 0.7294, 0.7137,  ..., 0.7882, 0.8000, 0.7922],
         [0.7294, 0.7294, 0.7098,  ..., 0.7490, 0.7647, 0.7608],
         ...,
         [0.7961, 0.7961, 0.7647,  ..., 0.6745, 0.6784, 0.6745],
         [0.7804, 0.7922, 0.7647,  ..., 0.6706, 0.6745, 0.6667],
         [0.7843, 0.7961, 0.7608,  ..., 0.6706, 0.6706, 0.6667]],

        [[0.5804, 0.5804, 0.5608,  ..., 0.6235, 0.6431, 0.6510],
         [0.5765, 0.5725, 0.5490,  ..., 0.6000, 0.6235, 0.6353],
         [0.5725, 0.5686, 0.5451,  ..., 0.5451, 0.5765, 0.5922],
         ...,
         [0.5529, 0.5412, 0.4667,  ..., 0.4941, 0.4863, 0.4824],
         [0.5255, 0.5176, 0.4510,  ..., 0.4902, 0.4824, 0.4745],
         [0.5216, 0.5137, 0.4431,  ..., 0.4902, 0.4784, 0.4706]],

        [[0.6510, 0.6667, 0.6706,  ..., 0.6353, 0.6471, 0.6431],
         [0.6627, 0.6706, 0.6706,  ..., 0.6235, 0.6353, 0.6392],
         [0.6824, 0.6784, 0.6667,  ..., 0.5843, 0.6000, 0.

In [95]:
img2 = ski.io.imread(img_path)
img2 = color.rgb2hed(img2)
img2 = transf_to_tensor()(img2)
# img2 = img2.squeeze()
img2.shape

torch.Size([3, 768, 1024])

In [88]:
img2.dtype

torch.float32

In [96]:
img2

tensor([[[0.0420, 0.0390, 0.0373,  ..., 0.0501, 0.0478, 0.0484],
         [0.0395, 0.0379, 0.0368,  ..., 0.0514, 0.0497, 0.0485],
         [0.0355, 0.0363, 0.0373,  ..., 0.0576, 0.0551, 0.0541],
         ...,
         [0.0788, 0.0798, 0.0871,  ..., 0.0330, 0.0316, 0.0321],
         [0.0830, 0.0836, 0.0916,  ..., 0.0327, 0.0305, 0.0315],
         [0.0843, 0.0849, 0.0913,  ..., 0.0327, 0.0310, 0.0307]],

        [[0.0024, 0.0043, 0.0070,  ..., 0.0000, 0.0000, 0.0000],
         [0.0043, 0.0057, 0.0084,  ..., 0.0000, 0.0000, 0.0000],
         [0.0070, 0.0071, 0.0083,  ..., 0.0006, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0155, 0.0178, 0.0179],
         [0.0000, 0.0000, 0.0000,  ..., 0.0159, 0.0187, 0.0188],
         [0.0000, 0.0000, 0.0000,  ..., 0.0159, 0.0188, 0.0199]],

        [[0.0133, 0.0137, 0.0154,  ..., 0.0014, 0.0025, 0.0029],
         [0.0140, 0.0144, 0.0164,  ..., 0.0031, 0.0025, 0.0041],
         [0.0151, 0.0148, 0.0168,  ..., 0.0053, 0.0046, 0.

In [71]:
hsv_img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
hsv_img = transfToTensor(hsv_img)
hsv_img = hsv_img.permute(1,2,0)
hsv_img

error: OpenCV(4.9.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'


In [107]:
data_path = 'dataset_run'
classes = 0

In [108]:
dataset2 = datasets.ImageFolder(root=data_path, transform=transforms.Compose([transforms.ToTensor()]))

In [73]:
dataset2[0][0].dtype

torch.float32

In [110]:
# for img, label in dataset2:
#     print(img.shape)

In [111]:
import math
math.ceil(0.2)

1

In [69]:
dataset2[0][0]

tensor([[[0.6510, 0.6667, 0.6706,  ..., 0.6353, 0.6471, 0.6431],
         [0.6627, 0.6706, 0.6706,  ..., 0.6235, 0.6353, 0.6392],
         [0.6824, 0.6784, 0.6667,  ..., 0.5843, 0.6000, 0.6039],
         ...,
         [0.5098, 0.5059, 0.4706,  ..., 0.6745, 0.6824, 0.6784],
         [0.4902, 0.4902, 0.4549,  ..., 0.6745, 0.6863, 0.6784],
         [0.4863, 0.4863, 0.4549,  ..., 0.6745, 0.6824, 0.6824]],

        [[0.5804, 0.5804, 0.5608,  ..., 0.6235, 0.6431, 0.6510],
         [0.5765, 0.5725, 0.5490,  ..., 0.6000, 0.6235, 0.6353],
         [0.5725, 0.5686, 0.5451,  ..., 0.5451, 0.5765, 0.5922],
         ...,
         [0.5529, 0.5412, 0.4667,  ..., 0.4941, 0.4863, 0.4824],
         [0.5255, 0.5176, 0.4510,  ..., 0.4902, 0.4824, 0.4745],
         [0.5216, 0.5137, 0.4431,  ..., 0.4902, 0.4784, 0.4706]],

        [[0.7294, 0.7333, 0.7216,  ..., 0.8078, 0.8078, 0.8039],
         [0.7294, 0.7294, 0.7137,  ..., 0.7882, 0.8000, 0.7922],
         [0.7294, 0.7294, 0.7098,  ..., 0.7490, 0.7647, 0.

In [49]:
def hsv_image_loader(image_path):
    img = cv2.imread(image_path)
    hsv_img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    hsv_img = transf_to_tensor()(hsv_img)
    hsv_img = hsv_img.permute(1,2,0)
    return hsv_img

In [63]:
def hed_image_loader(image_path):
    img = ski.io.imread(image_path)
    hed_img = color.rgb2hed(img)
    hed_img = transf_to_tensor()(hed_img)
    # hed_img = hed_img.permute(1, 2, 0)
    return hed_img

In [64]:
dataset = datasets.ImageFolder(root=data_path, loader=hed_image_loader)

In [70]:
dataset.dtype

AttributeError: 'ImageFolder' object has no attribute 'dtype'

In [66]:
dataset[0][0].shape

torch.Size([3, 768, 1024])

In [67]:
dataset[0][0]

tensor([[[0.0420, 0.0390, 0.0373,  ..., 0.0501, 0.0478, 0.0484],
         [0.0395, 0.0379, 0.0368,  ..., 0.0514, 0.0497, 0.0485],
         [0.0355, 0.0363, 0.0373,  ..., 0.0576, 0.0551, 0.0541],
         ...,
         [0.0788, 0.0798, 0.0871,  ..., 0.0330, 0.0316, 0.0321],
         [0.0830, 0.0836, 0.0916,  ..., 0.0327, 0.0305, 0.0315],
         [0.0843, 0.0849, 0.0913,  ..., 0.0327, 0.0310, 0.0307]],

        [[0.0024, 0.0043, 0.0070,  ..., 0.0000, 0.0000, 0.0000],
         [0.0043, 0.0057, 0.0084,  ..., 0.0000, 0.0000, 0.0000],
         [0.0070, 0.0071, 0.0083,  ..., 0.0006, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0155, 0.0178, 0.0179],
         [0.0000, 0.0000, 0.0000,  ..., 0.0159, 0.0187, 0.0188],
         [0.0000, 0.0000, 0.0000,  ..., 0.0159, 0.0188, 0.0199]],

        [[0.0133, 0.0137, 0.0154,  ..., 0.0014, 0.0025, 0.0029],
         [0.0140, 0.0144, 0.0164,  ..., 0.0031, 0.0025, 0.0041],
         [0.0151, 0.0148, 0.0168,  ..., 0.0053, 0.0046, 0.

In [43]:
classes

['1_Normal', '0_Amiloidose']

In [37]:
seed = np.random.randint(10)
seed

7

In [1]:
# X_generator = torch.Generator().manual_seed(seed)
# X_train, X_test = random_split(X, [0.7 * len(X), 0.3 * len(X)], generator=X_generator)

# X_test

In [ ]:
y_generator = torch.Generator().manual_seed(seed)


In [14]:
for x in X:
    print(x)

20
25
22
24
19
17
22


In [15]:
for yi in y:
    print(yi)

18
29
11


In [ ]:
def data_prep(base_dir):
    

In [74]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [75]:
def hsv_img_loader_fn(device):
    def hsv_image_loader(image_path):
        img = cv2.imread(image_path)
        hsv_img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
        hsv_img = transf_to_tensor()(hsv_img)
        # hsv_img = hsv_img.permute(1,2,0)
        return hsv_img.to(device)
    
    return hsv_image_loader

In [76]:
hsv_fn = hsv_img_loader_fn(device)

In [78]:
tensor_img = hsv_fn(img_path)
tensor_img.dtype

torch.float32