In [1]:
import numpy as np

In [17]:
a_range = np.random.randint(10,20,10)
print(a_range)

[18 13 15 16 19 15 13 11 15 15]


In [20]:
a_range

array([18, 13, 15, 16, 19, 15, 13, 11, 15, 15])

In [19]:
permutation = np.random.permutation(10)
print(permutation)

[1 0 7 4 6 9 8 5 2 3]


In [22]:
perm_range = a_range[permutation]
perm_range

array([13, 18, 11, 19, 13, 15, 15, 15, 15, 16])